# Emma Tu, Mindy Yun
# Contributions: Emma - 50%, Mindy - 50%

# Generate Cypher Key
def generate_cypher_key(shift):
    """This function takes a shift value as input and generates a monoalphabetic cipher key. 
    It first defines the English alphabet, then creates a shifted version of the alphabet by slicing it. 
    The shifted alphabet is combined with the remaining part of the alphabet, creating a one-to-one mapping 
    between original and shifted letters. This mapping is stored in a dictionary and returned as the cipher key."""
    alphabet = 'abcdefghijklmnopqrstuvwxyz'     # define alphabet
    shifted_alphabet = alphabet[shift:] + alphabet[:shift]  # from shift to end and start to shift
    alphabet_dict = {}              # dictionary original:shifted
    for i in range(len(alphabet)):
        alphabet_dict[alphabet[i]] = shifted_alphabet[i]  # create mapping
    return alphabet_dict

# Encrypt Message
def encrypt(message, key):
    """This function takes a message and the key generated by the previous function. 
    It iterates through each character in the message. If the character is a letter, 
    it checks if it is lowercase or uppercase and retrieves the corresponding replacement 
    letter from the cipher key. Non-alphabetic characters are included as they are. The 
    resulting encrypted message is returned."""
    encrypted_message = ''
    for i in range(len(message)):
        if message[i].isalpha():
            if message[i].islower():
                encrypted_message += key[message[i]]
            else:
                encrypted_message += key[message[i].lower()].upper()
        else:
            encrypted_message += message[i]
    return encrypted_message

# Decrypt Ciphertext
def decrypt(ciphertext, key):
    """Similar to the encryption process, this function takes a ciphertext and the key as input. 
    It creates a reverse key by swapping keys and values in the original key. Then, it iterates 
    through each character in the ciphertext. If the character is a letter, it retrieves the original 
    letter from the reverse key. Non-alphabetic characters are preserved. The decrypted message is returned."""

    decrypted_message = ''

    for i in range(len(ciphertext)):
        if ciphertext[i].isalpha():
            if ciphertext[i].islower():
                decrypted_message += {v: k for k, v in key.items()}[ciphertext[i]]
            else:
                decrypted_message += {v: k for k, v in key.items()}[ciphertext[i].lower()].upper()
        else:
            decrypted_message += ciphertext[i]
    return decrypted_message        


def main():
    shift = int(input("Enter shift value for cipher key (1-25): "))
    key = generate_cypher_key(shift)

    choice = input("Encrypt or decrypt? (e/d): ").lower()
    if choice == 'e':
        message = input("Enter message to encrypt: ")
        encrypted_message = encrypt(message, key)
        print("Encrypted message:", encrypted_message)   

    elif choice == 'd':
        ciphertext = input("Enter message to decrypt: ")
        decrypted_message = decrypt(ciphertext, key)
        print("Decrypted message:", decrypted_message)   

    else:
        print("Invalid choice. Please enter 'e' for encrypt or 'd' for decrypt.")

if __name__ == "__main__":
    main()